
CREATE DATABASE IF NOT EXISTS blood_donation;
USE blood_donation;

-- ACCOUNT TABLE

CREATE TABLE IF NOT EXISTS Account (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role ENUM('ADMIN', 'DOCTOR', 'PATIENT', 'DONOR', 'BANK_STAFF') NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- BLOOD_BANK TABLE

CREATE TABLE IF NOT EXISTS Blood_Bank (
    bank_id INT AUTO_INCREMENT PRIMARY KEY,
    bank_name VARCHAR(255) NOT NULL,
    contact_email VARCHAR(255) UNIQUE,
    contact_phone VARCHAR(15) NOT NULL,
    location VARCHAR(255) NOT NULL,
    capacity DECIMAL(10,2) CHECK (capacity > 0),
    assigned_doctor_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (assigned_doctor_id) REFERENCES Account(user_id) ON DELETE SET NULL
) ENGINE=InnoDB;
